<h3><b>Introduction to Data Analytics - Exercise set 1 - Python and NumPy Basics</b></h3>

In [53]:
import numpy as np
import numpy.ma as ma

<h4><b>1. Create these lists without NumPy:</b></h4>

- List of 15 ones

- List of 15 number 7's

- List of numbers from 100 to 150

- List of even numbers between 0 and 100

- List of years that are divisible by 4 between 1950 and 2020
<br>


In [54]:
# Creating list of ones using list comprehesnion
list_ones = [1 for number in range(15)]
print(f"{list_ones}, lenght = {len(list_ones)}")


[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], lenght = 15


In [55]:
# Creating list of sevens using while loop
list_sevens = []
while len(list_sevens) < 15:
  list_sevens.append(7)
print(f"{list_sevens}, lenght = {len(list_sevens)}")


[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7], lenght = 15


In [56]:
# List of numbers 100-150 using for loop
list_100 = []
for number in range(100, 151):
  list_100.append(number)
print(list_100)

[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150]


In [57]:
# List of even numbers between 0 and 100
# Using function range step feature

list_evens = [el for el in range(0, 101, 2)]  # Adds every second number in range 0-100
print(list_evens)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [58]:
# List of years that are divisible by 4 between 1950 and 2020
# Using list comprehension with if statement
list_divisebles = [el for el in range(1950,2021) if (el % 4) == 0]
print(list_divisebles)

[1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020]


<h4><b>2.	Now, create these arrays with NumPy!</b></h4>

- Array of 15 zeroes

- Array of 15 ones

- Array of 15 number 7's

- Array of numbers from 100 to 150

- Array of numbers from 1900 to 2021

- Array of even numbers between 0 and 100

- Array of years that are divisible by 4 between 1950 and 2020



In [59]:
# Array of 15 zeroes
a = np.zeros(15)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [60]:
# Array of 15 ones
b = np.ones(15)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [61]:
# Array of 15 number 7's
c = np.ones(15) * 7
c

array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])

In [62]:
# Array of numbers from 100 to 150
d = np.arange(100,151)
d

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [63]:
# Array of numbers from 1900 to 2021
e = np.arange(1900, 2022)
e

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021])

In [64]:
# Array of even numbers between 0 and 100
d = np.arange(0, 101, 2)
d

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [65]:
# Array of years that are divisible by 4 between 1950 and 2020
f = np.array([year for year in range(1950, 2021) if year % 4 == 0])
f

array([1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988, 1992,
       1996, 2000, 2004, 2008, 2012, 2016, 2020])

<h4><b style="color: red">Note: compare the NumPy code to the plain Python code after doing the exercises. Easier or more difficult? :) 
(answer in code comments or as text in Jupyter Notebook)</b></h4>

*It is way more easier than using loops.*

*But for me it is pretty close to list comprehesion if we are speaking about a bit more complex lists\arrays. For example these are pretty much the same:*
<pre>list_divisebles = [el for el in range(1950,2021) if (el % 4) == 0]</pre>
<pre>f = np.array([year for year in range(1950, 2021) if year % 4 == 0])</pre>
*Anyways I'm quite sure that numpy is better solution for even more complicated data like multidimensional arrays.*


<h3><b>3. Let's try out NumPy matrices:</b></h3>

- Create a 7x7 matrix, with values from 1 to 49

    - Extra task: Create this matrix (list of lists) without NumPy in Python!

<br>

- Generate 8x8 random number matrix, values between 0 and 5

- Generate 8x8 random number matrix, using standard normal distribution values (= values are between -3 and 3)


In [66]:
# 7x7 matrix, with values from 1 to 49

# Firstly creating list 1-49 and then reshaping ii into 7x7 matrix 
# using np.reshape()
np_matrix = np.arange(1,50).reshape(7,7)
np_matrix

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [67]:
# Extra task: Create this matrix (list of lists) without NumPy in Python!

# Firstly, creating 7x7 list of same lists 1-7
list_of_lists = [[el for el in range(1, 8)] for dimension in range(1,8)]

# Iterating through dimensions:
for ind, value in enumerate(list_of_lists):

  # Changing integers in lists to ones we need, with addition of
  # list index multiplied by lenght of list (always 7 in this case)
  for number in range(len(value)):
    list_of_lists[ind][number] += len(list_of_lists[ind]) * ind

  # This works because difference between for example every number 
  # of the first list and every number in the same position of the last list is
  # 42, which is multiplication of list index(6) and lenght of the list (7). 
list_of_lists

[[1, 2, 3, 4, 5, 6, 7],
 [8, 9, 10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19, 20, 21],
 [22, 23, 24, 25, 26, 27, 28],
 [29, 30, 31, 32, 33, 34, 35],
 [36, 37, 38, 39, 40, 41, 42],
 [43, 44, 45, 46, 47, 48, 49]]

In [68]:
# Generate 8x8 random number matrix, values between 0 and 5

random_matrix_8x8 = np.random.randint(0,6,(8, 8))
random_matrix_8x8

array([[3, 5, 3, 0, 0, 2, 5, 5],
       [5, 0, 4, 4, 5, 1, 1, 5],
       [4, 4, 0, 3, 0, 1, 0, 5],
       [3, 0, 0, 2, 1, 1, 3, 4],
       [3, 2, 4, 3, 3, 1, 1, 4],
       [2, 0, 3, 4, 4, 3, 0, 1],
       [0, 2, 5, 5, 4, 1, 5, 4],
       [2, 2, 4, 4, 2, 4, 5, 3]])

In [69]:
# Generate 8x8 random number matrix, using standard normal distribution values (= values are between -3 and 3)

st_distribution_8x8 = np.random.randn(8,8)
st_distribution_8x8

array([[ 1.02266637,  0.73225723,  2.22751802, -0.40845413, -0.04931749,
        -1.56105334,  0.02475347, -2.17224201],
       [ 0.92066496, -0.16835121, -0.13720674,  1.1795562 ,  0.61935316,
        -0.06838471,  0.47103913,  0.29763349],
       [ 0.02611602,  0.1930356 ,  0.28512529,  1.44364093, -0.28007575,
        -0.66720757, -0.49589599, -0.85748975],
       [-0.05374111, -0.22913383,  1.19401926,  0.21298625, -0.73098132,
         0.46104652,  1.29000571,  2.04057681],
       [-1.00574349,  1.94990821, -1.1233244 ,  1.04821392, -0.25922141,
         2.50811011, -0.50170447,  0.30427116],
       [-0.77372115, -1.30858817, -0.22575834, -1.29806635,  0.64879514,
        -0.59293386, -0.15138714, -0.60417304],
       [-1.87847866,  1.71601572, -0.99453975, -0.64277075,  0.83717052,
         0.95696622,  2.04296826,  0.5769497 ],
       [-0.19924916,  0.00616422, -1.75014139,  0.39523162,  0.16910473,
         0.43702064, -2.11603376, -0.14557345]])

<h3><b>4. Create a linearly spaced… </b></h3>

- array (list/vector) of 10 values between value 0 and 1

- 10x10 matrix between values 0 and 5

    - Extra task: create this matrix without NumPy as well!


<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/cubes.png"/>


In [70]:
# Array (list/vector) of 10 values between value 0 and 1
array_ten_values = np.linspace(0, 1, 10)
array_ten_values

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [71]:
# 10x10 matrix between values 0 and 5
np_matrix_10x10 = np.linspace(0, 5, 100).reshape(10, 10)
np_matrix_10x10

array([[0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
        0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545],
       [0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
        0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596],
       [1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
        1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646],
       [1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
        1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697],
       [2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
        2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747],
       [2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
        2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798],
       [3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
        3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848],
       [3.53535354, 3.58585859, 3.6363636

In [72]:
# Extra task: create this matrix (10x10, values betweeb 0 and 5) 
# without NumPy as well!

raw_list = []
nested_lists = []
counter = 0
# Let's findout what is our step:
step = 5 / 100

# Creating a list 0-5 with 100 steps
for el in range(0,101):
  el *= step
  raw_list.append(el)

# Than let's create a new version of it, 10 nested lists
while counter < len(raw_list):
  nested_lists.append(raw_list[counter : counter+10])
  counter += 10
nested_lists


[[0.0,
  0.05,
  0.1,
  0.15000000000000002,
  0.2,
  0.25,
  0.30000000000000004,
  0.35000000000000003,
  0.4,
  0.45],
 [0.5,
  0.55,
  0.6000000000000001,
  0.65,
  0.7000000000000001,
  0.75,
  0.8,
  0.8500000000000001,
  0.9,
  0.9500000000000001],
 [1.0,
  1.05,
  1.1,
  1.1500000000000001,
  1.2000000000000002,
  1.25,
  1.3,
  1.35,
  1.4000000000000001,
  1.4500000000000002],
 [1.5,
  1.55,
  1.6,
  1.6500000000000001,
  1.7000000000000002,
  1.75,
  1.8,
  1.85,
  1.9000000000000001,
  1.9500000000000002],
 [2.0,
  2.0500000000000003,
  2.1,
  2.15,
  2.2,
  2.25,
  2.3000000000000003,
  2.35,
  2.4000000000000004,
  2.45],
 [2.5,
  2.5500000000000003,
  2.6,
  2.6500000000000004,
  2.7,
  2.75,
  2.8000000000000003,
  2.85,
  2.9000000000000004,
  2.95],
 [3.0,
  3.0500000000000003,
  3.1,
  3.1500000000000004,
  3.2,
  3.25,
  3.3000000000000003,
  3.35,
  3.4000000000000004,
  3.45],
 [3.5,
  3.5500000000000003,
  3.6,
  3.6500000000000004,
  3.7,
  3.75,
  3.80000000000

<h3><b>5. Recreate the matrices in code based on the pictures.</b></h3>

- Create this 3x5 matrix with NumPy:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix1.png"/>

Note: The values above have no logic, you'll have to feed basic Python lists to NumPy for this result


In [73]:
list1 = [23, 34, 54 ,31, 75]
list2 = [33, 56, 78, 65, 97]
list3 = [41, 32, 11, 39, 51]

recreate_array1 = np.array([list1, list2, list3])
recreate_array1

array([[23, 34, 54, 31, 75],
       [33, 56, 78, 65, 97],
       [41, 32, 11, 39, 51]])

- Generate this NumPy array:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix2.png" width="800"/>

In [74]:
# exercise 1.5b, generate NumPy array / matrix

recreate_array_2 = np.array(range(128,256)).reshape(8,16)
recreate_array_2

array([[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
        173, 174, 175],
       [176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
        189, 190, 191],
       [192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
        205, 206, 207],
       [208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
        221, 222, 223],
       [224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
        237, 238, 239],
       [240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
        253, 254, 255]])

- Generate this NumPy array:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix3.png" width="500"/>

<b>Tips:</b> arange-function (and step-parameter) + reshape is recommended. Alternatively you can use broadcasting and division if you like.

In [75]:
# exercise 1.5c, generate NumPy array / matrix
recreate_array3 = np.arange(0.05, 5.05, 0.05).reshape(10,10)
recreate_array3

array([[0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ],
       [0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ],
       [1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ],
       [1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ],
       [2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 ],
       [2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  ],
       [3.05, 3.1 , 3.15, 3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45, 3.5 ],
       [3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 , 3.85, 3.9 , 3.95, 4.  ],
       [4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35, 4.4 , 4.45, 4.5 ],
       [4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95, 5.  ]])

<h3><b>6. Use this matrix in your code:</b></h3>

dataset = np.arange(1, 37).reshape(6, 6)

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix4.png"/>


In [76]:
# exercise 1.6a, matrix slicing
dataset = np.arange(1, 37).reshape(6, 6)
dataset

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

- Create a slice of the matrix that contains this part of the matrix:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix5.png"/>

In [77]:
# exercise 1.6b, matrix slicing

slice_b = np.array(dataset[3:,2:])
slice_b

array([[21, 22, 23, 24],
       [27, 28, 29, 30],
       [33, 34, 35, 36]])

- Pick out this column slice from data

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/series1.png"/>

In [78]:
# exercise 1.6c, matrix slicing

slice_c = np.array(dataset[0:4,3])
slice_c

array([ 4, 10, 16, 22])

- Pick out this row from the data

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/series2.png"/>

In [79]:
# exercise 1.6d, matrix slicing

slice_d = np.array(dataset[2])
slice_d

array([13, 14, 15, 16, 17, 18])

- Pick out these three rows from data:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix6.png"/>

In [80]:
# exercise 1.6e, matrix slicing

slice_e = np.array(dataset[3:])
slice_e

array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

<h3><b>7. Use this matrix:</b></h3>

<b>dataset_2 = np.arange(1, 50).reshape(7, 7)</b>

- Add 50 to all values in the array (use broadcasting)

- Get the sum of all values in the dataset

- Get sum of only odd numbers in the dataset

- Get the standard deviation of the values in the dataset

- Get the sum of all values by ROW in the dataset

- Get the sum of all values by COLUMN in the dataset (tip, use the axis –parameter)

<br>

- <b>Extra task:</b> Do the total sum, row sum and column sum exercises< <b>without</b> NumPy in Python!

<br><br>
<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/desktopcomputer.png"/>


In [81]:
# exercise 1.7, NumPy -operations on a matrix
dataset_2 = np.arange(1, 50).reshape(7, 7)
dataset_2

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [82]:
# Add 50 to all values in the array (use broadcasting)

z = dataset_2 + 50
z

array([[51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

In [83]:
# Get the sum of all values in the dataset

x = np.sum(dataset_2)
x

1225

In [84]:
# Get sum of only odd numbers in the dataset
filtered_data = dataset_2[dataset_2 % 2 ==0]
y = np.sum(filtered_data)
y

600

In [85]:
# Get the standard deviation of the values in the dataset
deviation = np.std(dataset_2)
deviation

14.142135623730951

In [86]:
# Get the sum of all values by ROW in the dataset

# Firstly split dataset in seperate rows
vertical = np.vsplit(dataset_2, 7)
# Then count sum of each row
for el in vertical:
  print(f"{el} - Sum = {np.sum(el)}") 

# OR
rows_sum = np.sum(dataset_2, axis=1)
rows_sum

[[1 2 3 4 5 6 7]] - Sum = 28
[[ 8  9 10 11 12 13 14]] - Sum = 77
[[15 16 17 18 19 20 21]] - Sum = 126
[[22 23 24 25 26 27 28]] - Sum = 175
[[29 30 31 32 33 34 35]] - Sum = 224
[[36 37 38 39 40 41 42]] - Sum = 273
[[43 44 45 46 47 48 49]] - Sum = 322


array([ 28,  77, 126, 175, 224, 273, 322])

In [87]:
# Get the sum of all values by COLUMN in the dataset (tip, use the axis –parameter)
columns_sum = np.sum(dataset_2, axis=0)
columns_sum

array([154, 161, 168, 175, 182, 189, 196])

<br><br>
<h2><b>Advanced extra tasks for extra points (varying challenges, some require Googling):</b></h2>

<h3><b>1. Create two files for this exercise: save_matrix.py and read_matrix.py</b></h3>

- in save_matrix.py: create a 15x15 matrix, and save it to a file (matrix.txt)
 - in read_matrix.py, read matrix.txt, and convert it back to a NumPy matrix

NumPy has loadtxt() and savetxt()-functions for these purposes.


In [88]:
# advanced extra exercise 1
from save_matrix import save_matrix
from read_matrix import read_matrix

save_matrix()
read_matrix()


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


<h3><b>2. Masked arrays are a feature of NumPy that allow us to deal with pieces data that are incorrect or missing in a dataset (for example, faulty measurements from equipment etc.).</b></h3>

Create a NumPy matrix, that contains numbers between 0 to 50, and put some faulty numbers in a 10 different spots 
(for example: -100)

Use a masked array to handle the -100 values in your matrix. Replace every -100 with 0.


In [89]:
# advanced extra exercise 2
# Creates a list 0-50 with everty fifth object equal to -100
data_raw = [el if (el % 5) != 0 else -100 for el in range(0,51)]

# Reshaping the list into 3x17 numpy matrix
extra_2_data = np.array(data_raw).reshape(3,17)

# numpy.ma.masked_less Return an array masked where condition is True
# In this case every value greater then 0 will be True
masked = ma.masked_less(extra_2_data, 0)

# ma.filled() fills every False value with given new value
result = masked.filled(0)
result

array([[ 0,  1,  2,  3,  4,  0,  6,  7,  8,  9,  0, 11, 12, 13, 14,  0,
        16],
       [17, 18, 19,  0, 21, 22, 23, 24,  0, 26, 27, 28, 29,  0, 31, 32,
        33],
       [34,  0, 36, 37, 38, 39,  0, 41, 42, 43, 44,  0, 46, 47, 48, 49,
         0]])

<h3><b>3. argsort is a feature of NumPy  that allows you to sort a NumPy array based on another NumPy array. </b></h3>

This is useful if you have two separate arrays, but their data  should be in sync even if order of data is changed. For example, one array contains the prices of cars, and another contains the manufacturing years. If we wish to sort the data by manufacturing years, and keep the prices in sync as well, argsort will be handy.

Useful link:
http://arogozhnikov.github.io/2015/09/29/NumpyTipsAndTricks1.html

Create two random datasets:

- Manufacturing years of 10 cars, values between 2010 and 2020

- Selling price of 10 cars, prices between 2000€ and 60000€

Use argsort to sort both datasets according to manufacturing years.


In [90]:
# advanced extra exercise 3
# Creates array with manufacturing years
years = np.random.randint(2010,2021, 10)
# Creates array with random prices
sell_prices = np.random.randint(2000,60000, 10)
sorter = np.argsort(years)

print(years[sorter])
print(sell_prices[sorter])

[2010 2012 2012 2013 2015 2016 2017 2017 2019 2020]
[12646 21524 24639  4695 23359 58656 36017 33805 19569 19169]


<h3><b>4. Try out the following additional NumPy features, and discuss in your code comments or in Jupyter Notebook text where they could be useful. You can also Google and search for ideas where these could be used. </b></h3>

You can write your thoughts as comments in the code or Jupyter text as you try out each feature.

- np.repeat()

- np.ravel()

- np.hsplit(), np.vsplit(), np.hstack, np.vstack()

- np.transpose()

- np.round()

- np.expand_dims(), np.squeeze()

- np.digitize()




<div align="center"><h1>np.repeat()</h></div>

Function repeat() could be usefull in cases when you want to create a list of same values and don't want to use ones(), zeros() or broadcasting for that.

In [91]:
np.repeat(5,5)


array([5, 5, 5, 5, 5])

Or you can repeat every element of the array

In [92]:
random_array = np.arange(3)
print(f"Here is original array - {random_array}")
repeat_random_array = np.repeat(random_array, 2)
print(f"And this is repeated array - {repeat_random_array}")

Here is original array - [0 1 2]
And this is repeated array - [0 0 1 1 2 2]


Also you can duplicate rows using axis parameter!

In [93]:
random_array_2d = np.arange(10).reshape(2, 5)
print(f"Here is original array - {random_array_2d}")
repeat_rows = np.repeat(random_array_2d, 2, 0)
print(f"And this is array with repeated rows :\n"
      f"{repeat_rows}")

Here is original array - [[0 1 2 3 4]
 [5 6 7 8 9]]
And this is array with repeated rows :
[[0 1 2 3 4]
 [0 1 2 3 4]
 [5 6 7 8 9]
 [5 6 7 8 9]]


<div align="center"><h1>np.ravel()</h></div>

Ravel is used to flatten the elements of multidimensional array into 1-dimensional.
It might be usefull when you want to join arrays in certain order

In [94]:
data_for_ravel = np.arange(10).reshape(2,5)
data_for_ravel

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

You can use different order parameters:

In [95]:
# By default it uses "C" or row first order. 
ravel_example = np.ravel(data_for_ravel)
ravel_example

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
# "F" order for flattening by column:
np.ravel(data_for_ravel, order="F")

array([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

Also with ravel() you can flatten usual Python lists!

In [97]:
random_list = [[1, 2, 3], [4, 5, 6]]
np.ravel(random_list)

array([1, 2, 3, 4, 5, 6])

By the way, ravel() has a brother from another mother - method flatten().

Difference between them is that ravel() is a function while flatten() is a method. 
Also, ravel creates only view of object, so broadcasting works here. Flatten produces a true copy of object 

In [98]:
flatten_example = data_for_ravel.flatten()
flatten_example

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
# Let's change our data:
data_for_ravel[0,0] = 100

In [100]:
# Flatten created a copy of array 
# which is not affected by any changes
print(flatten_example)
# Ravel affected by the changes
print(ravel_example)

[0 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]


<div align="center"><h1>np.hsplit(), np.vsplit(), np.hstack, np.vstack()</h></div>


These splits might be used in cases where you would like to split matrix into different arrays vertically or horizontally. For example if data is too heavy and you want to process it in batches or if you need only one piece of data at the moment. 

In order to combine arrays or to bring the splitted pieces back to the original shape you can use stack functions. 


<div align="center"><h1>np.transpose()</h></div>

The np.transpose() function is used in NumPy to transpose the dimensions of an array. Transposing an array means rearranging its axes to a different order. This can be useful when working with arrays of different shapes and sizes, and can also be used to manipulate and reshape arrays for computation or data analysis.

<div align="center"><h1>np.round()</h></div>

This function works element-wise, meaning it rounds each element in the array separately. It can be useful when working with floating-point numbers and you want to round them to a certain precision, or when you want to convert floating-point numbers to integers.

<div align="center"><h1>np.expand_dims() and np.squeeze()</h></div>

This functions could be used for converting data into needed format. For example TensorFlow module requires converting oftenly

<div align="center"><h1>np.digitize()</h></div>

A function in the NumPy library that returns the indices of the bins to which each value in an input array belongs. It can be used to discretize continuous data into a specified number of bins or categories. 